(function(){try{var h=this;function k(a,c){var b=aa;return!!a||(b.log(c),!1)}function ba(a){return a}function l(a,c){for(var b=c.split(".");b.length&&a;)a=a[b.shift()];return a}function n(a,c){if(!Array.isArray(a))return!1;c=c||ba;for(var b=0,d=a.length;b<d;b++)if(!0===c(a[b]))return!0;return!1}function p(a,c,b){a=l(a,c);return"string"===typeof a?a:b||""}function q(a,c){var b=l(a,c);return Array.isArray(b)?b:[]}function r(a,c){for(var b=q(a,c),d=[],e=0,f=b.length;e<f;e++)d.push(t(b[e])?b[e]:{});return d}
function ca(a,c){if(!Array.isArray(a))return null;for(var b=0;b<a.length;b++){var d=a[b];if(c(d))return d}return null}function t(a){return!(!a||a.constructor!==Object)};function u(a,c){var b=(h.ButtonWebConfig||{})[a];return void 0===b?c:b}function x(a,c){var b=u(a,c);return"string"===typeof b?b:c||""}function y(a,c){var b=u(a,c);return"boolean"===typeof b?b:c||!1}function z(a){a=u(a);if("function"===typeof a)return a};var A=void 0;function B(){return"try{"+x("siteCatalyst","s")+".tl(true,'e','usebutton')}catch(e){}"}function da(){void 0===A&&(A="function"===typeof l(h,x("siteCatalyst","s")+".tl"));return A}function fa(){return[/Android/i,/webOS/i,/iPhone/i,/iPad/i,/iPod/i,/BlackBerry/i,/Windows Phone/i].some(function(a){return!!navigator.userAgent.match(a)})}function C(){try{return(new Intl.DateTimeFormat).resolvedOptions().timeZone}catch(a){return null}};function ga(a,c){for(var b in c){var d=c[b];"[object Object]"===Object.prototype.toString.call(d)?ga(a[b],d):a[b]=d}}function ha(a,c){var b=document.createElement(a),d=Array.prototype.splice.call(arguments,1);"a"===a&&(b.rel="noskim",b.setAttribute("data-bttnio-link",1),da()&&b.setAttribute("onclick",B()));for(var e=0,f=d.length;e<f;e++)for(var g in d[e])d[e].hasOwnProperty(g)&&(b.style[g]=d[e][g]);return b}
function E(a,c){var b,d=ha(a);ga(d,c);b=b||[];for(var e=0,f=b.length;e<f;++e)d.appendChild(b[e]);return d};var ia=/^(?:track\.bttn\.io\/([^\/]+).*|(?!track)([^\.]+)\.bttn\.io(?:\/.*|$))/,F=ha("a");function H(a){return a.replace(/^www./,"").toLowerCase()}function ja(){var a={},c=F.search.replace(/^\?/,"").split("&"),b,d,e;b=0;for(d=c.length;b<d;b++)e=c[b].split("="),a[e[0]]=decodeURIComponent(e[1]||"");return a}
function ka(a){var c=a.dataset.bttnioTargetHref;if(void 0!==c)return c;var c=u("relativeLinkLocation"),c=t(c)?c:null,b=document.createElement("a");b.href="/";c=null===c||b.hostname!==a.hostname?{hostname:a.hostname,port:a.port}:{hostname:p(c,"hostname",a.hostname),port:p(c,"port",a.port)};F.href=a.href;F.hostname=c.hostname;c.port&&(F.port=c.port);return F.href}
function la(a,c){var b=c.links_configuration,d=ka(a);F.href=d;var e=H(F.hostname),f=F.pathname,g=ja();if(!b||a.getAttribute("data-bttnio-enhanced")||a.getAttribute("data-bttnio-link"))return!1;var m=r(b,"supported_hostnames");if(n(m,function(a){return e===H(p(a,"hostname"))}))return!0;d=r(b,"supported_bttnio_subdomains");if(d.length){var v=(e+f).match(ia);if(v){var w=v[1]||v[2];if(n(d,function(a){return w.toLowerCase()===p(a,"subdomain")}))return!0}}b=r(b,"supported_affiliates");return n(b,function(a){if(e!==
H(p(a,"hostname")))return!1;var b=r(a,"query_url_keys"),b=n(b,function(a){a=p(a,"key");if(g.hasOwnProperty(a)){var b=H(E("a",{href:g[a]}).hostname);return n(m,function(a){return b===H(p(a,"hostname"))})}return!1}),c=r(a,"query_ids"),c=n(c,function(a){var b=p(a,"key");return g.hasOwnProperty(b)?(a=r(a,"values"),n(a,function(a){return p(a,"value")===g[b]})):!1});a=r(a,"pathname_ids");a=n(a,function(a){var b=p(a,"regex"),c;if(!b)return!1;try{c=(new RegExp(b)).exec(f)}catch(d){return!1}if(c){var e=c.slice(1);
a=r(a,"matches");return n(a,function(a){a:if(a=q(a,"values"),Array.isArray(e)&&Array.isArray(a)&&e.length===a.length){var b,c;b=0;for(c=e.length;b<c;b++)if(e[b]!==a[b]){a=!1;break a}a=!0}else a=!1;return a})}return!1});return b||c||a})};function ma(a){try{return h.JSON.stringify(a)}catch(c){return"{}"}};function na(a){var c=h.XMLHttpRequest,b=I;this.a=a;this.c=c;this.b=b}
function oa(a,c,b,d,e,f){var g=new a.c;g.onreadystatechange=function(){if(4===g.readyState&&"function"===typeof f){var b=g.responseText,c=a.b,d;try{(d=h.JSON.parse(b))&&d.constructor===Object||(d={})}catch(e){c.log("Invalid JSON:"+b),d={}}f(d)}};g.open(c,a.a+b);if(Array.isArray(e))for(c=0;c<e.length;c++)g.setRequestHeader(e[c].H,e[c].value);g.setRequestHeader("X-BTNVersion","2.8.4");d&&g.setRequestHeader("Content-Type","application/json");g.send(d?ma(d):void 0)}
function pa(a,c,b){oa(a,"GET",c,null,null,b)}function J(a,c,b,d,e){oa(a,"POST",c,b,d,e)};function K(a){a+="=";var c=document.cookie.split(";"),b,d;for(b=0;b<c.length;b++){for(d=c[b];" "===d.charAt(0);)d=d.substring(1,d.length);if(0===d.indexOf(a))return d.substring(a.length,d.length)}}function L(a,c,b,d){a=[a+"="+c,"path=/","max-age="+(void 0===b?31536E3:b)];d&&"string"===typeof d&&0<d.trim().length&&a.push("domain=."+d);document.cookie=a.join(";")};function N(a){a=l(a,"search")||"";return(/^[?]/.test(a)?a.slice(1):a).split("&").reduce(function(a,b){var d=b.split("="),e=h.decodeURIComponent(d[0]||""),d=h.decodeURIComponent(d[1]||"");e&&(a[e]=d);return a},{})};function O(a){L("bttnreferrertoken",a,void 0,x("referrerCookieDomain"))}function qa(a){L("btn_js_widget_enrollment_id",a)}function ra(){var a=h.location,c=N(a).btn_ref;c&&O(c);(a=N(a).btn_enrollment_id)&&qa(a)}function P(){return K("bttnreferrertoken")}function Q(){return K("btn_js_widget_enrollment_id")};function R(a,c){"function"===typeof a&&a.apply(h,Array.prototype.slice.call(arguments,1))};var sa={};function S(a,c){var b=window.sessionStorage;if(b&&a&&"function"===typeof b.setItem)try{var d=h.JSON.stringify(c);"string"===typeof d&&b.setItem(a,d)}catch(e){}}function T(a){var c=window.sessionStorage;if(c&&a&&"function"===typeof c.getItem)try{var b=c.getItem(a);return b?h.JSON.parse(b):void 0}catch(d){return null}};function ta(a,c,b){var d=[],e=u("userIdentifier"),f,g;f=0;for(g=c.length;f<g;f++)d.push({pub_ref:c[f].dataset.bttnioPubRef,href:ka(c[f])});a={application_id:a,links:d};b&&(a.session_id=b);e&&(a.thirdparty_id=e);return a}
function U(a,c,b,d,e){this.f=V();this.l=c;this.m=b;this.b=d;this.a=a;this.g=e;this.i=!!K("bttnlockout");this.h=null;this.c=[];this.j=!1;this.f&&this.a.log("Restored sessionId: "+this.f);ra();if(this.i)this.a.log("bttnlockout cookie found: platform is not supported");else{var f=this;u("enhanceLinks")&&ua(this.b,function(a){f.h=a;f.refresh()});va(f.g);h.setTimeout(function(){xa(f.g)&&ya(f.b,function(a){f.g.b=a;za(f.g)&&Aa(f.b,a,function(a){a?Ba(f.g):f.a.log("Widget could not be displayed. Please review the campaign!")})})},
500);u("enableAutomaticActivityReporting")&&Ca(f.b);(a=u("siteCatalyst"))&&"function"!==typeof h[a].tl&&this.a.log("Invalidate SiteCatalyst detected: "+a+".tl is not a function")}}function Da(a){if(!a.h)return[];var c=[].slice.call(document.querySelectorAll(x("linkSelector","a"))),b=[],d,e;d=0;for(e=c.length;d<e;d++)la(c[d],a.h)&&b.push(c[d]);return b.slice(0,50)}
U.prototype.refresh=function(a){var c=this,b=x("applicationId");c.i?c.a.log("Unsupported platform; will not make requests"):b?(c.c=Da(c),1>c.c.length||(b=ta(b,c.c,c.f),J(c.l,"/v1/web-session/get-buttons",b,null,function(b){if("error"in b)c.a.log("Error enhancing links: "+l(b,"error.message")),R(a,!1,[]);else{var e=l(b,"object.supported_os");c.j||(c.j=!0,R(z("onLoad"),e));if(e){var e=l(b,"object.links")||[],f=e.length,g=p(b,"object.session_id");b=[];c.f&&g===c.f||c.a.log("Initiating new session: "+
g);c.f=g;L("bttnsessionid",g);if(f===c.c.length)for(g=0;g<f;g++)e[g]&&(c.c[g].href=e[g],c.c[g].setAttribute("rel","noskim"),c.c[g].setAttribute("data-bttnio-enhanced",1),da()&&c.c[g].setAttribute("onclick",B()));R(z("onButtonsLoaded"),b);R(a,!0,b)}else c.a.log("Received unsupported platform signal. Will set bttnlockout cookie"),L("bttnlockout","1",14400)}}))):c.a.log("Error: No applicationId present in ButtonWebConfig!")};U.prototype.logout=function(){L("bttnsessionid","",0)};
U.prototype.reportEvent=function(a,c,b){W(this.b,a,c,b)};U.prototype.getReferrerToken=function(){return P()};U.prototype.reportOrder=function(a,c){if(t(a)){var b=x("applicationId");if(b){var b=h.btoa(b+":"),d=P(),e=y("reportAllOrders");d||e?(d&&(a.btn_ref=d),J(this.m,"/v1/mobile-order",a,[{H:"Authorization",value:"Basic "+b}],function(a){"function"===typeof c&&c(a)})):this.a.log("Missing btn_ref")}else this.a.log("Missing ButtonWebConfig.application_id")}else this.a.log("Invalid order, cannot post")};
U.prototype.reportProductView=function(a,c){var b=window.location.href,d=l(a,"categories");d&&Array.isArray(d)||(d=[]);Ea(this.b,b,d,c)};U.prototype.setCustomerId=function(a){a&&null!==a&&""!==a?"string"===typeof a?(L("bttncustomerid",a),W(this.b,"btn:customer-identified")):this.a.log('An invalid customer ID (not of type "string" or undefined/null) was provided, and could not be stored'):(L("bttncustomerid","",0),W(this.b,"btn:customer-deidentified"))};U.prototype.getCustomerId=function(){return K("bttncustomerid")};
U.prototype.subscribePhoneNumber=function(a,c){return Fa(this.b,a,c)};U.prototype.setPageSmsCampaigningTag=function(a){var c=null;"string"===typeof a&&0<a.length&&(c=a);sa.pageSmsCampaigningTag=c};U.prototype.tagUser=function(a,c){Ea(this,{a:a},c)};var Ga={position:"fixed",display:"block",height:"0","max-width":"440px",filter:"drop-shadow(0px -8px 20px rgba(0, 0, 0, 0.1))",transition:"ease 0.65s","z-index":"9999",border:"0"},Ha={position:"fixed",top:"0",height:"100vh",width:"100vw",background:"#222222",opacity:"0.6","z-index":"9998"},X=Object.freeze({s:"btn_js_widget_type",A:"btn_js_widget_type_single_display",B:"btn_js_widget_type_sticky_display",D:"btn_js_widget_display_occurred",F:"btn_js_widget_interaction_occurred",C:"btn_js_widget_dismiss_occurred",
w:"btn_js_widget_holdout_group",o:"btn_js_site_page_view_count",v:"btn_js_widget_phone_enrolled",u:"bttncustomerid"});
function Ia(){var a=I,c=Ja;this.a=a;this.c=this.b=null;this.m=function(b){b&&document.body.appendChild(b);L(X.D,"true",1800);switch(l(this.b,"onsite_style.widget_type")){case "sticky":L(X.s,X.B,1800);break;default:L(X.s,X.A,1800)}a.log("Widget is ready!")};this.l=function(b,c){var e=l(b,"data.arguments.height");c.style.height=e+"px";c.style.width="100%";c.height=e+"px";c.width="100%";a.log("Resetting widget height: "+e)};this.i=function(){L(X.F,"true",1800);a.log("User interacted with the widget")};
this.h=function(b){b=l(b,"data.arguments.phoneNumber");Ka(c,b,this.b,function(a){L(X.v,"true");qa(a)});a.log("Collecting phone number: "+b)};this.g=function(b){(b=l(b,"data.arguments.url"))&&window.location.replace(b);a.log("Opening URL: "+b)};this.j=function(b){var d=l(b,"data.arguments.eventName");b=l(b,"data.arguments.eventBody");d?W(c,d,b,function(b){b?a.log("Successfully reported event: "+d):a.log("Could not report event: "+d)}):a.log("No event name provided!")};this.f=function(b,d,e){var f=
this;b=l(b,"data.arguments.delay")||0;h.setTimeout(function(){d&&d.parentNode&&d.parentNode.removeChild(d);e&&e.parentNode&&e.parentNode.removeChild(e);if(f.c){window.removeEventListener("message",f.c);f.c=null;L(X.C,"true",2592E3);var a=l(f.b,"smscampaign_id"),b=l(f.b,"onsite_style.template");W(c,"btn:web-widget-dismissed",{promotion_source_token:P(),smscampaign_id:a,template_url:b},function(a){a?f.a.log("btn:web-widget-dismissed event was successfully reported!"):f.a.log("Could not report btn:web-widget-dismissed event!")})}},
Number(b));a.log("Dismissing widget after "+b+" ms")}}
function xa(a){if(!u("enableSmsCollection"))return a.a.log("Brand has not enabled SMS Collection. Should not be shown!"),!1;if(K(X.v))return a.a.log("User phone number already enrolled. Should not be shown!"),!1;if(K(X.w))return a.a.log("User is in holdout group. Should not be shown!"),!1;var c=K(X.s);return K(X.D)&&c===X.A?(a.a.log("Single view widget was displayed in the last 30 mins. Should not be shown!"),!1):K(X.F)&&c===X.B?(a.a.log("Sticky widget was displayed in the last 30 mins. Should not be shown!"),!1):
K(X.C)?(a.a.log("Widget was dismissed in the last 30 days. Should not be shown!"),!1):!0}
function za(a){if(!a.b)return a.a.log("Currently ineligible due to missing SMS campaign"),!1;var c=l(a.b,"onsite_display_conditions.page_view_count"),b=T(X.o);if(c&&"number"===typeof c&&b<c)return a.a.log("Inhibited display due to insufficient page view count"),!1;var c=window.location.pathname,b=c+window.location.search,d=K(X.u),e=l(a.b,"onsite_display_conditions.page_pattern_denylist");if(e&&Array.isArray(e))for(var f=0;f<e.length;f++){var g=new RegExp(e[f]);if(g.test(c)||g.test(b))return a.a.log("Inhibited display due to matching a pathname that matches a denylist entry"),
!1}if((f=l(a.b,"onsite_display_conditions.customer_identity_state"))&&(!d&&"identified"===f||d&&"unidentified"===f))return!1;if((d=l(a.b,"onsite_display_conditions.page_pattern_allowlist"))&&Array.isArray(d)&&d.length){for(f=0;f<d.length;f++)if(e=new RegExp(d[f]),e.test(c)||e.test(b))return!0;a.a.log("Inhibited display due to not matching any allowlist entries");return!1}return!0}
function va(a){var c=T(X.o);"number"!==typeof c||"number"===typeof c&&c!==c?(a.a.log("Reset page view count due to seeing a non-numeric value"),S(X.o,1)):S(X.o,c+1)}
function Ba(a){var c=fa(),b=l(a.b,"onsite_style.template")||"https://cdn.usebutton.com/web-widgets/SmsCollectionV1.html",d=E("iframe",{className:"btn___widget",src:b+"?origin="+window.location.protocol+"//"+window.location.host,height:0,style:Object.assign({},Ga,c?{bottom:"0"}:{top:"50%",left:"50%",transform:"translate(-50%, -50%)"})}),e=c?null:E("div",{className:"btn___widget_bg",style:Ha});e&&e.addEventListener("click",function(){a.f(null,d,e)});var f=!1;a.c=function(c){if(c&&b.startsWith(c.origin)){var m=
l(c,"data.name");if(m)switch(m){case "Button.web.onReady":f||(a.m(e),f=!0);break;case "Button.web.resetDimensions":a.l(c,d);break;case "Button.web.registerInteraction":a.i();break;case "Button.web.collectPhoneNumber":a.h(c);break;case "Button.web.openURL":a.g(c);break;case "Button.web.reportEvent":a.j(c);break;case "Button.web.dismissWidget":a.f(c,d,e);break;default:a.a.log("Unsupported message received: "+m)}}};window.addEventListener("message",a.c);d.addEventListener("load",function(){var c=l(a.b,
"onsite_style"),e=l(a.b,"experimental_values"),f=u("applicationId"),w=P(),G=C(),D=window.location.href,M,ea=T("btn_js_sms_campaign");ea&&(M=l(ea,"value"),M=l(M,"smscampaign_id"));c=Object.assign({},c,{applicationId:f,sourceToken:w,smsCampaignId:M,timezone:G,currentUrl:D},e);try{d.contentWindow.postMessage(c,b)}catch(wa){a.a.log("Error injecting data to the widget: "+wa)}});document.body.appendChild(d);a.a.log("Attempting to load widget found at: "+b)};var La=/^sess-/;function Ma(){var a=Na,c=Oa;this.a=I;this.b=a;this.G=c;this.I=!!K("bttnlockout");this.j=this.i=this.g=this.l=this.f=this.h=this.c=!1;this.m=function(a){var c=V();(a=l(a,"object.session_id"))&&"string"===typeof a&&a!==c&&(this.a.log("Refreshing session ID: "+a),L("bttnsessionid",a))};this.J=function(a){(a=l(a,"object.source_token"))&&O(a)}}function V(){var a=K("bttnsessionid");return La.test(a)?a:void 0}
function ua(a,c){var b=u("applicationId");b?a.c||(a.c=!0,pa(a.b,"/v1/web-session/config?application_id="+b,function(b){a.c=!1;R(c,l(b,"object")||null)})):a.a.log("Missing ButtonWebConfig.application_id")}
function W(a,c,b,d){var e=V(),f=P(),g=Q(),m=window.location.href,v=K("bttncustomerid");t(b)&&(b.hasOwnProperty("promotion_source_token")||(b.promotion_source_token=f),b.hasOwnProperty("sms_enrollment_id")||(b.sms_enrollment_id=g),b.hasOwnProperty("url")||(b.url=m),b.hasOwnProperty("cid")||(b.cid=v));e?a.I?a.a.log("Platform not supported, will not report events"):a.h||(a.h=!0,J(a.b,"/v1/web-session/events",{session_id:e,thirdparty_id:v,events:[{name:c,value:t(b)?b:void 0}]},null,function(b){a.h=!1;
b="ok"===l(b,"meta.status");R(d,b)})):a.a.log("Cannot report event. Missing session ID!")}
function ya(a,c){var b=u("applicationId"),d=P(),e=V(),f=sa.pageSmsCampaigningTag||void 0;if(b){var g=T("btn_js_sms_campaign"),m=l(g,"value"),v=l(g,"continue_fetching"),w=l(g,"fetched_at"),G=h.Date.now()-w;if(g&&!v&&w&&18E5>G)R(c,m);else{g=T(X.o);if("number"!==typeof g||"number"===typeof g&&g!==g)g=1;m=!1;K(X.u)&&(m=!0);v=window.location.pathname+window.location.search;if(!a.f){a.f=!0;var w=N(h.location),G={},D;for(D in w)w.hasOwnProperty(D)&&(G[D]=D.startsWith("utm_")||D.startsWith("btn_")?w[D]:null);
J(a.b,"/v1/web-session/collection-campaign/eligibility",{application_id:b,session_id:e,source_token:d,page_query:G,page_tag:f,customer_identity_state:m,page_view_count:g,combined_pathname_search_string:v},null,function(b){a.f=!1;a.m(b);var d=l(b,"object.smscampaign");b=l(b,"object.continue_fetching");S("btn_js_sms_campaign",{fetched_at:h.Date.now(),continue_fetching:b||!1,value:d});R(c,d)})}}}else a.a.log("Missing ButtonWebConfig.application_id")}
function Aa(a,c,b){var d=V(),e=P();c=l(c,"smscampaign_id");var f=window.location.href;d?a.l||(a.l=!0,J(a.b,"/v1/web-session/collection-campaign/display",{session_id:d,source_token:e,smscampaign_id:c,current_url:f},null,function(c){a.l=!1;a.m(c);a.J(c);var d=l(c,"object.source_token");c=l(c,"object.holdout");var e;try{e=JSON.parse(c)}catch(f){e=!1}(e="boolean"===typeof e?e:!1)&&L(X.w,"true",31536E3);R(b,e?!1:!!d)})):a.a.log("Missing session ID!")}
function Ka(a,c,b,d){var e=V(),f=P(),g=l(b,"smscampaign_id");b=l(b,"onsite_style.template");var m=C();e?a.g||(a.g=!0,J(a.b,"/v1/web-session/collection-campaign/enrollment",{session_id:e,source_token:f,phone_number:c,smscampaign_id:g,timezone:m,template:b},null,function(b){a.g=!1;a.m(b);var c=null;try{var e=l(b,"object.enrollments")||[],c=ca(e,function(a){return a&&!!a.collection}).collection}catch(f){a.a.log("Failed to extract enrollment ID from response! "+f)}R(d,c)})):a.a.log("Missing session ID!")}
function Ea(a,c,b,d){var e=V(),f=Q(),g=P();e?g?f?b&&b.length?a.j||(a.j=!0,J(a.G,"/v1/activity/web/product-view",{url:c,categories:b,session_id:e,enrollment_id:f,btn_ref:g},null,function(){a.j=!1;R(d)})):a.a.log("Skipping product view report because there are no reported categories"):a.a.log("Skipping product view report because the user is not enrolled"):a.a.log("Missing source token!"):a.a.log("Missing session ID!")}
function Ca(a){var c=window.location.href,b=V(),d=Q(),e=P();b?e?d?a.i||(a.i=!0,J(a.G,"/v1/activity/web/pageview",{url:c,session_id:b,enrollment_id:d,btn_ref:e},null,function(){a.i=!1;R(void 0)})):a.a.log("Skipping page view report because the user is not enrolled"):a.a.log("Missing source token!"):a.a.log("Missing session ID!")}
function Fa(a,c,b){var d=u("applicationId"),e=V(),f=C(),g=window.location.href,m=K("bttncustomerid");c||a.a.log("Missing phone number.");return J(a.b,"/v1/web-session/collection-campaign/enrollment/headless",{application_id:d,phone_number:c,timezone:f,session_id:e,current_url:g,customer_id:m},null,function(c){var d=l(c,"meta.status");if("ok"===d){var e=l(c,"object.source_token");e?O(e):a.a.log("No source_token present on response object.");(c=l(c,"object.session_id"))?L("bttnsessionid",c):a.a.log("No session_id present on response object.")}b&&
b({ok:"ok"===d})})};function Pa(a){this.a=a}Pa.prototype.log=function(a){this.a&&h.console&&h.console.log("[Button]",a)};var Y=h.__bttnio||"bttnio",I=new Pa(y("enableLogging",!1));
if(l(h,Y+".ok"))I.log("The ButtonJS snippet was loaded multiple times");else{var Qa=l(h,Y+".q")||[],Na=new na("https://web.usebutton.com"),Oa=new na("https://api.usebutton.com"),Ja=new Ma,Ra=new Ia,aa=I,Z=k(h.XMLHttpRequest,"No XMLHttpRequest")&&k(h.JSON,"No native JSON support")?new U(I,Na,Oa,Ja,Ra):{};h[Y]=function(){var a=[].slice.call(arguments),c=a.shift();if(c&&"function"===typeof Z[c])return I.log(c+"("+a.join(",")+")"),Z[c].apply(Z,a)};for(h[Y].ok=!0;Qa.length;)h[Y].apply(this,Qa.shift())};}catch(e){}})();
